name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang make flawfinder cppcheck

    - name: Run flawfinder
      run: |
        flawfinder --context src/

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=constVariable --suppress=variableScope --suppress=knownConditionTrueFalse --error-exitcode=1 src/

    - name: Build
      run: |
        make CC=clang

    - name: Check binary exists
      run: |
        test -x ./meowsh
        file ./meowsh
